#!/bin/bash

1=${1?Error: no run name given} #how do i name the resultant files run name $n_file_name 
2=${2?Error: no subsample percentage given} 
3=${3?Error: no minsize given}
4=${4?Error: no alpha given}

args=("$@") 
       directory  subsample  minsize   alpha  
echo ${args[0]} ${args[1]} ${args[2]} ${args[3]} #probably do not need to do this

mkdir /home/matthew/diss_runs/${args[0]}

cd ${args[0]}

if [ $n2 < 100 ]; then
  Thomassubsample_script home/matthew/files_for_master_bashscript/4_mbc_derep.fasta parameter here ${args[1]}? output subsampled_percentagen_mbc.fasta 
  vsearch --cluster_unoise subsampled_percentagen_mbc.fasta  --minsize $n3 --unoise_alpha $n4 --centroids 5_mbc_denoise.fasta
  rm subsampled_percentage_mbc.fasta 
else 
vsearch --cluster_unoise home/matthew/files_for_master_bashscript/4_mbc_derep.fasta --minsize ${args[2]} --unoise_alpha ${args[3]} --centroids 5_mbc_denoise.fasta
fi
 
echo "Step 3: Length Filtering"
vsearch --fastx_filter 5_mbc_denoise.fasta --fastq_minlen 418 --fastq_maxlen 418 -fastaout 6_mbc_indelfil.fasta
rm 5_mbc_denoise.fasta

echo "Step 4: Translation Filtering"
filtertranslate -i 6_mbc_indelfil.fasta -t 5 
rm *transfail.fa
mv 6_mbc_indelfil_transpass.fa 7_mbc_transpass.fasta
rm 6_mbc_indelfil_transpass.fa

echo "Step 5: Chimera Filtering"
vsearch --uchime3_denovo 7_mbc_transpass.fasta --nonchimeras 8_mbc_final.fasta
rm 7_mbc_transpass.fasta

echo "Step 6: Coleoptera ASV filtering by Thomas's Script"
home/matthew/files_for_master_bashscript./Thomas_filterscript coleoptera_master_asv_file 8_mbc_final.fasta -output 9_mbc_beetle_coleop.fasta 
rm 8_mbc_final.fasta

echo "Step 7: OTU Delimitation"
vsearch --cluster_size 9_mbc_beetle_coleop.fasta --sizein --relabel otu --id 0.97 --centroids ${args[0]}_otus.fasta

echo "Step 8: Reads Mapping"
vsearch --usearch_global home/matthew/files_for_master_bashscript/3_mbc_concat.fasta (this needs changing?) -db ${args[0]}_otus.fasta -id 0.97 -otutabout ${args[0]}_coleop_reads_map.tsv


-figure the outputs, which all go into the r script

where does taxonomy come into this? coleoptera asv filtering?

needs all three variables in the r script
-metadata
-reads
-taxonomy

what does the r script output? put into n/n_results?

-also needs adipart script and check_expected_richness

cd../ 
